### ISSUE TITLE
Question, does it return a string for example dusk, noon, night 

### ISSUE THREAD

**Issue by AlmogRnD** [mikljacq/solar_calculator#3]
Hi, 
I wanted to know what data is returned and if you return a string of the times of day i.e. noon, night

**Comment by mikljacq** [comment]
Hello,

It does not return the time of day, it returns the time for a given solar event I would say.

The returned object is a custom Instant object, which is like a DateTime but it handles timezones in a more flexible way.
The Twilight object is just an object encapsulating 2 Instant objects (start and end).

**Comment by AlmogRnD** [comment]
ok thanks
